/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Frames;

import LMS.ConnectionProvider;
import java.sql.*;
import java.sql.Statement;
import javax.swing.*;
import java.sql.Connection;
import java.sql.ConnectionBuilder;

/**
 *
 * @author ifti
 */
public class Add_Student extends javax.swing.JFrame {

    /**
     * Creates new form Add_Student
     */
    public Add_Student() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        nameTXT = new javax.swing.JTextField();
        fatherTXT = new javax.swing.JTextField();
        nicTXT = new javax.swing.JTextField();
        deptCombo = new javax.swing.JComboBox<>();
        contactTXT = new javax.swing.JTextField();
        semesterCombo = new javax.swing.JComboBox<>();
        savebtn = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        sessionTXT = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));

        jLabel1.setIcon(new javax.swing.ImageIcon("/home/ifti/NetBeansProjects/LMS/src/Image/student.png")); // NOI18N

        nameTXT.setBackground(new java.awt.Color(0, 204, 204));
        nameTXT.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        nameTXT.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "NAME", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP));

        fatherTXT.setBackground(new java.awt.Color(0, 204, 204));
        fatherTXT.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        fatherTXT.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "FATHER NAME", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP));
        fatherTXT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fatherTXTActionPerformed(evt);
            }
        });

        nicTXT.setBackground(new java.awt.Color(0, 204, 204));
        nicTXT.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        nicTXT.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "CNIC", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP));

        deptCombo.setBackground(new java.awt.Color(0, 204, 204));
        deptCombo.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        deptCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "NULL", "CS & IT", "LLB", "BBA" }));
        deptCombo.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "DEPARTMENT", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP));
        deptCombo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        deptCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deptComboActionPerformed(evt);
            }
        });

        contactTXT.setBackground(new java.awt.Color(0, 204, 204));
        contactTXT.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        contactTXT.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "CONTACT", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP));
        contactTXT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contactTXTActionPerformed(evt);
            }
        });

        semesterCombo.setBackground(new java.awt.Color(0, 204, 204));
        semesterCombo.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        semesterCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", " " }));
        semesterCombo.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "SEMESTER", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP));
        semesterCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                semesterComboActionPerformed(evt);
            }
        });

        savebtn.setBackground(new java.awt.Color(153, 255, 153));
        savebtn.setIcon(new javax.swing.ImageIcon("/home/ifti/NetBeansProjects/LMS/src/Image/save.png")); // NOI18N
        savebtn.setText("SAVE");
        savebtn.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        savebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                savebtnActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(250, 148, 148));
        jButton2.setIcon(new javax.swing.ImageIcon("/home/ifti/NetBeansProjects/LMS/src/Image/cross.png")); // NOI18N
        jButton2.setText("CLOSE");
        jButton2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        sessionTXT.setBackground(new java.awt.Color(0, 204, 204));
        sessionTXT.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        sessionTXT.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "SESSION", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP));
        sessionTXT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sessionTXTActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(531, 531, 531)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(370, 370, 370)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(contactTXT, javax.swing.GroupLayout.DEFAULT_SIZE, 433, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(savebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(nameTXT, javax.swing.GroupLayout.DEFAULT_SIZE, 433, Short.MAX_VALUE)
                            .addComponent(sessionTXT, javax.swing.GroupLayout.DEFAULT_SIZE, 433, Short.MAX_VALUE)
                            .addComponent(deptCombo, 0, 433, Short.MAX_VALUE)
                            .addComponent(fatherTXT, javax.swing.GroupLayout.DEFAULT_SIZE, 433, Short.MAX_VALUE)
                            .addComponent(semesterCombo, 0, 433, Short.MAX_VALUE)
                            .addComponent(nicTXT))))
                .addContainerGap(357, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel1)
                .addGap(44, 44, 44)
                .addComponent(nicTXT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(nameTXT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(fatherTXT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(deptCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(sessionTXT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(semesterCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(contactTXT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(savebtn)
                    .addComponent(jButton2))
                .addGap(64, 64, 64))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fatherTXTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fatherTXTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fatherTXTActionPerformed

    private void contactTXTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contactTXTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_contactTXTActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        dispose();    }//GEN-LAST:event_jButton2ActionPerformed

    private void deptComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deptComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deptComboActionPerformed

    private void savebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savebtnActionPerformed
        String nic = nicTXT.getText().toString().trim();
        String name = nameTXT.getText().toString().trim();
        String fathername = fatherTXT.getText().toString().trim();
        String dept = (String) deptCombo.getSelectedItem().toString();
        String session = sessionTXT.getText().toString().trim();
        String semester = (String) semesterCombo.getSelectedItem().toString();
        String contact = contactTXT.getText().toString().trim();
        try {
            Connection con = (Connection) ConnectionProvider.getCon();
            String query = "INSERT INTO Student"
                    + "VALUES('" + nic + "','" + name + "','" + fathername + "',"
                    + "'" + dept + "','" + session + "','" + semester + "','" + contact + "')";
            PreparedStatement statement
                    = con.prepareStatement("INSERT INTO Student"
                    + "VALUES('" + nic + "','" + name + "','" + fathername + "',"
                    + "'" + dept + "','" + session + "','" + semester + "','" + contact + "')");
//Statement statement = con.createStatement();

            statement.executeUpdate(query);
            JOptionPane.showMessageDialog(null, "added  sucessfully...");
          //  setVisible(false);
          //  new Add_Student().setVisible(true);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "additon  failed...");
          //  setVisible(false);
          //  new Add_Student().setVisible(true);
            System.out.println(e);
           e.printStackTrace();

        }
        

    }//GEN-LAST:event_savebtnActionPerformed

    private void semesterComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_semesterComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_semesterComboActionPerformed

    private void sessionTXTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sessionTXTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sessionTXTActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Add_Student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Add_Student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Add_Student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Add_Student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Add_Student().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField contactTXT;
    private javax.swing.JComboBox<String> deptCombo;
    private javax.swing.JTextField fatherTXT;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField nameTXT;
    private javax.swing.JTextField nicTXT;
    private javax.swing.JButton savebtn;
    private javax.swing.JComboBox<String> semesterCombo;
    private javax.swing.JTextField sessionTXT;
    // End of variables declaration//GEN-END:variables
}
