/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Frames;

import java.sql.ResultSet;
import java.sql.DriverManager;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author ifti
 */
public class Status extends javax.swing.JFrame {

    /**
     * Creates new form States
     */
    public Status() {
        initComponents();
        try {

            String user = "iftidev";
            String password = "balochistan";
            String url = "jdbc:mysql://localhost:3306/LMS";
            Class.forName("com.mysql.cj.jdbc.Driver");

            java.sql.Connection con = DriverManager.getConnection(url, user, password);

            java.sql.Statement st = con.createStatement();
//            ResultSet rs = st.executeQuery("select * from STUDENT, ISSUE_BOOK");

//            ResultSet rs = st.executeQuery("SELECT  LMS.ISSUE_BOOK.STU_ID, LMS.STUDENT.`NAME`, LMS.ISSUE_BOOK.BOOK_ID,"
//                    + "LMS.ISSUE_BOOK.ISSUE_DATE, LMS.ISSUE_BOOK.RETURN_STATUS, LMS.ISSUE_BOOK.RETURN_DATE"
//                    + "FROM LMS.ISSUE_BOOK INNER JOIN LMS.STUDENT ON LMS.ISSUE_BOOK.STU_ID= LMS.STUDENT.SID ");


            ResultSet rs = st.executeQuery("SELECT  LMS.ISSUE_BOOK.STU_ID, "
                    + "LMS.STUDENT.`NAME`,"
                    + " LMS.ISSUE_BOOK.BOOK_ID, "
                    + "LMS.ISSUE_BOOK.ISSUE_DATE, "
                    + "LMS.ISSUE_BOOK.RETURN_STATUS, "
                   
            + " LMS.ISSUE_BOOK.RETURN_DATE "
                    + " FROM LMS.ISSUE_BOOK JOIN LMS.STUDENT "
                    + "ON LMS.ISSUE_BOOK.STU_ID = LMS.STUDENT.SID");
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            //            ResultSet rs = st.executeQuery("SELECT LMS.ISSUE_BOOK.ISSUE_ID, LMS.ISSUE_BOOK.STU_ID, LMS.ISSUE_BOOK.BOOK_ID,LMS.STUDENT.SID,LMS.STUDENT.`NAME`"
            //                    + "FROM LMS.ISSUE_BOOK"
            //                    + "INNER JOIN LMS.STUDENT"
            //                    + "ON LMS.ISSUE_BOOK.STU_ID= LMS.STUDENT.SID ;");
            //        ("SELECT issue_id, student_id, book_id, issue_date, return_status"
            //                    + " FROM LMS.ISSUE_BOOK, LMS.Student.S_id, LMS.Student.name "
            //                    + "FROM LMS.ISSUE_BOOK "
            //                    + "JOIN LMS.Student ON LMS.ISSUE_BOOK.student_id = LMS.Student.S_id");
            issueTable.setModel(DbUtils.resultSetToTableModel(rs));

        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        issueTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Status");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        jLabel1.setText("Book Status");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 30, -1, -1));

        jButton1.setBackground(new java.awt.Color(250, 148, 148));
        jButton1.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        jButton1.setText("Close");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 680, 157, -1));

        issueTable.setBackground(new java.awt.Color(0, 204, 204));
        issueTable.setFont(new java.awt.Font("DejaVu Sans", 0, 18)); // NOI18N
        issueTable.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jScrollPane1.setViewportView(issueTable);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 1380, 600));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1404, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Status.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Status.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Status.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Status.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Status().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable issueTable;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
