/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Frames;

import LMS.ConnectionProvider;
import java.beans.Statement;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import javax.swing.table.DefaultTableModel;
import java.sql.PreparedStatement;
import java.util.*;

/**
 *
 * @author ifti
 */
public class Status extends javax.swing.JFrame {

    /**
     * Creates new form States
     */
    public Status() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        issuedTblScroll = new javax.swing.JScrollPane();
        issueTbl = new javax.swing.JTable();
        returnedTblScroll = new javax.swing.JScrollPane();
        returnedTbl = new javax.swing.JTable();
        issuedRefreshBtn = new javax.swing.JButton();
        returnedrefreshBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Status");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        jLabel1.setText("Issued Books");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(487, 25, -1, -1));

        jLabel2.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        jLabel2.setText("Returned Books");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(483, 371, -1, -1));

        jButton1.setBackground(new java.awt.Color(250, 148, 148));
        jButton1.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        jButton1.setText("Close");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(459, 719, 157, -1));

        issuedTblScroll.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                issuedTblScrollKeyPressed(evt);
            }
        });

        issueTbl.setBackground(new java.awt.Color(0, 204, 204));
        issuedTblScroll.setViewportView(issueTbl);

        jPanel1.add(issuedTblScroll, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 65, 1060, 270));

        returnedTbl.setBackground(new java.awt.Color(0, 204, 204));
        returnedTblScroll.setViewportView(returnedTbl);

        jPanel1.add(returnedTblScroll, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 411, 1060, 270));

        issuedRefreshBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                issuedRefreshBtnActionPerformed(evt);
            }
        });
        jPanel1.add(issuedRefreshBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 39, -1, -1));
        jPanel1.add(returnedrefreshBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 371, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void issuedTblScrollKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_issuedTblScrollKeyPressed
//        try {
//               String user = "iftidev";
//            String password = "balochistan";
//            String url = "jdbc:mysql://localhost:3306/LMS";
//            Class.forName("com.mysql.cj.jdbc.Driver");
//
//            java.sql.Connection con = DriverManager.getConnection(url, user, password);
//
////            Connection con = (Connection) ConnectionProvider.getCon();
//          //  java.sql.Statement statement = (java.sql.Statement) con.createStatement();
//            
//PreparedStatement statement = con.prepareStatement("SELECT * FROM STUDENT");
//				
//ResultSet rs = statement.executeQuery();
//				
//displayTable.setModel(DbUtils.resultSetToTableModel(rs));
//            
//        } catch (Exception e) {
//        }
//  

    }//GEN-LAST:event_issuedTblScrollKeyPressed

    private void issuedRefreshBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_issuedRefreshBtnActionPerformed

        try {
   String user = "iftidev";
            String password = "balochistan";
            String url = "jdbc:mysql://localhost:3306/LMS";
            Class.forName("com.mysql.cj.jdbc.Driver");

            java.sql.Connection con = DriverManager.getConnection(url, user, password);

//            Connection con = (Connection) ConnectionProvider.getCon();
            Statement st = (Statement) con.createStatement();
            String sql = "select * from BOOK ";

            ResultSet rs = null;
            st.execute();
            ResultSetMetaData rsmd = null;
            rs.getMetaData();
            DefaultTableModel model = (DefaultTableModel) issueTbl.getModel();
            int cols = rsmd.getColumnCount();
            String[] colName = new String[cols];
            for (int i = 0; i < cols; i++) {
                colName[i] = rsmd.getColumnName(i + 1);

            }
            model.setColumnIdentifiers(colName);
            String id, first, last, age;
            while (rs.next()) {
                id = rs.getString(1);
                first = rs.getString(2);
                last = rs.getString(3);
                age = rs.getString(4);
                String[] row = {"id", "name", "author", "department"};
                model.addRow(row);
            }

            con.close();

        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_issuedRefreshBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Status.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Status.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Status.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Status.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Status().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable issueTbl;
    private javax.swing.JButton issuedRefreshBtn;
    private javax.swing.JScrollPane issuedTblScroll;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTable returnedTbl;
    private javax.swing.JScrollPane returnedTblScroll;
    private javax.swing.JButton returnedrefreshBtn;
    // End of variables declaration//GEN-END:variables
}
