/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Frames;

import java.sql.DriverManager;
import javax.swing.JOptionPane;

/**
 *
 * @author ifti-baloch
 */
public class UpdateStudent extends javax.swing.JFrame {

    /**
     * Creates new form updateTest
     */
    public UpdateStudent() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        idtxt = new javax.swing.JTextField();
        newIDtxt = new javax.swing.JTextField();
        nametxt = new javax.swing.JTextField();
        fnametxt = new javax.swing.JTextField();
        contactxt = new javax.swing.JTextField();
        deptComBox = new javax.swing.JComboBox<>();
        sessiontxt = new javax.swing.JTextField();
        semesterComBox = new javax.swing.JComboBox<>();
        deleteBtn = new javax.swing.JButton();
        updateBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));

        idtxt.setBackground(new java.awt.Color(0, 204, 204));
        idtxt.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        idtxt.setBorder(javax.swing.BorderFactory.createTitledBorder("ID"));

        newIDtxt.setBackground(new java.awt.Color(0, 204, 204));
        newIDtxt.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        newIDtxt.setBorder(javax.swing.BorderFactory.createTitledBorder("New ID"));
        newIDtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newIDtxtActionPerformed(evt);
            }
        });

        nametxt.setBackground(new java.awt.Color(0, 204, 204));
        nametxt.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        nametxt.setBorder(javax.swing.BorderFactory.createTitledBorder("Name"));

        fnametxt.setBackground(new java.awt.Color(0, 204, 204));
        fnametxt.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        fnametxt.setBorder(javax.swing.BorderFactory.createTitledBorder("Father Name"));

        contactxt.setBackground(new java.awt.Color(0, 204, 204));
        contactxt.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        contactxt.setBorder(javax.swing.BorderFactory.createTitledBorder("Contact"));

        deptComBox.setBackground(new java.awt.Color(0, 204, 204));
        deptComBox.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        deptComBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CS & IT", "BBA", "LAW" }));
        deptComBox.setBorder(javax.swing.BorderFactory.createTitledBorder("Department"));

        sessiontxt.setBackground(new java.awt.Color(0, 204, 204));
        sessiontxt.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        sessiontxt.setBorder(javax.swing.BorderFactory.createTitledBorder("Session"));

        semesterComBox.setBackground(new java.awt.Color(0, 204, 204));
        semesterComBox.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        semesterComBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7" }));
        semesterComBox.setBorder(javax.swing.BorderFactory.createTitledBorder("semester"));

        deleteBtn.setBackground(new java.awt.Color(250, 148, 148));
        deleteBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Frames/cross.png"))); // NOI18N
        deleteBtn.setText("cancel");
        deleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtnActionPerformed(evt);
            }
        });

        updateBtn.setBackground(new java.awt.Color(153, 255, 153));
        updateBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Frames/save.png"))); // NOI18N
        updateBtn.setText("update");
        updateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBtnActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        jLabel1.setText("Please fill all the columns correctly");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(updateBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(deleteBtn)
                .addGap(47, 47, 47))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(sessiontxt)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(semesterComBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(nametxt)
                    .addComponent(fnametxt, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(contactxt)
                    .addComponent(deptComBox, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(idtxt)
                    .addComponent(newIDtxt, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1)
                .addContainerGap(15, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel1)
                .addGap(35, 35, 35)
                .addComponent(idtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(newIDtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(nametxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fnametxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(contactxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(deptComBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sessiontxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(semesterComBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deleteBtn)
                    .addComponent(updateBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void updateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBtnActionPerformed
        String new_id = newIDtxt.getText();
        String old_id = idtxt.getText();
        String name = nametxt.getText();
        String fName = fnametxt.getText();
        String contact = contactxt.getText();
        String session = sessiontxt.getText();
        String dept = (String) deptComBox.getSelectedItem();
        String semester = (String) semesterComBox.getSelectedItem();
     

        try {
            String user = "iftidev";
            String password = "balochistan";
            String url = "jdbc:mysql://localhost:3306/LMS";
            Class.forName("com.mysql.cj.jdbc.Driver");

            java.sql.Connection con = DriverManager.getConnection(url, user, password);
            String update = "UPDATE  LMS.STUDENT SET S_ID='"+new_id+"' S_NAME ='" + name + "',"
                    + " F_NAME = '" + fName + "',PHONE_NO='" + contact + "', SESSION='" + session + "', SEMESTER='" + semester + "',"
                    + "S_DEPT='" + dept + "' WHERE S_ID = '" + old_id + "'";
            java.sql.Statement st = con.createStatement();
            st.execute(update);
            JOptionPane.showMessageDialog(null, "updated successfully");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
            System.out.println(e);
        }


    }//GEN-LAST:event_updateBtnActionPerformed

    private void deleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtnActionPerformed

    setVisible(false);

    }//GEN-LAST:event_deleteBtnActionPerformed

    private void newIDtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newIDtxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_newIDtxtActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UpdateStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UpdateStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UpdateStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UpdateStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UpdateStudent().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField contactxt;
    private javax.swing.JButton deleteBtn;
    private javax.swing.JComboBox<String> deptComBox;
    private javax.swing.JTextField fnametxt;
    private javax.swing.JTextField idtxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField nametxt;
    private javax.swing.JTextField newIDtxt;
    private javax.swing.JComboBox<String> semesterComBox;
    private javax.swing.JTextField sessiontxt;
    private javax.swing.JButton updateBtn;
    // End of variables declaration//GEN-END:variables
}
